---
docker_gpg_key: "https://download.docker.com/linux/ubuntu/gpg"
docker_repository: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
docker_user: "vagrant"
