---
grafana_version: "10.2.2"
grafana_port: 3000
grafana_admin_user: admin
grafana_admin_password: admin
grafana_domain: localhost

# Prometheus datasource
prometheus_url: "http://localhost:9090"
prometheus_datasource_name: "Prometheus"

# Loki datasource
loki_url: "http://localhost:3100"
loki_datasource_name: "Loki"
