---
galaxy_info:
  author: Doul Sy
  description: Docker installation role
  company: "Your Company"
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - docker
    - container

dependencies: []
