---
docker_ce_version: "5:20.10.24~3-0~ubuntu-jammy"
docker_ce_cli_version: "5:20.10.24~3-0~ubuntu-jammy"
containerd_version: "1.6.20-1"
docker_compose_version: "1.29.2"
django_image: timurbabs/django
django_port: 8000
static_volume: static
media_volume: media
