---
galaxy_info:
  author: Doul Sy
  description: Spring Boot application deployment with Prometheus metrics
  company: "Your Company"
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - java
    - spring-boot
    - application
    - prometheus

dependencies: []
