---
prometheus_version: "2.48.0"
prometheus_user: prometheus
prometheus_group: prometheus
prometheus_install_dir: /opt/prometheus
prometheus_config_dir: /etc/prometheus
prometheus_data_dir: /var/lib/prometheus
prometheus_port: 9090
prometheus_retention_time: "15d"

# Scrape targets
prometheus_scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.56.30:8080']

# Alertmanager configuration
alertmanager_enabled: true
alertmanager_url: 'http://localhost:9093'
