---
galaxy_info:
  author: Doul Sy
  description: Alertmanager for Prometheus alerts handling and notification
  company: "Your Company"
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - monitoring
    - alertmanager
    - prometheus
    - alerting

dependencies: []
