---
galaxy_info:
  author: Doul Sy
  description: Grafana installation and configuration for monitoring visualization
  company: "Your Company"
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - monitoring
    - grafana
    - visualization
    - dashboard

dependencies: []
