---
- name: Create alertmanager group
  group:
    name: "{{ alertmanager_group }}"
    state: present

- name: Create alertmanager user
  user:
    name: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
    shell: /bin/false
    system: yes
    create_home: no

- name: Create alertmanager directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
    mode: '0755'
  loop:
    - "{{ alertmanager_install_dir }}"
    - "{{ alertmanager_config_dir }}"
    - "{{ alertmanager_data_dir }}"

- name: Check if Alertmanager is already installed
  stat:
    path: "{{ alertmanager_install_dir }}/alertmanager"
  register: alertmanager_binary

- name: Download and install Alertmanager
  when: not alertmanager_binary.stat.exists
  block:
    - name: Download Alertmanager
      get_url:
        url: "https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
        dest: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
        mode: '0644'

    - name: Extract Alertmanager
      unarchive:
        src: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
        dest: /tmp/
        remote_src: yes

    - name: Copy Alertmanager binaries
      copy:
        src: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64/{{ item }}"
        dest: "{{ alertmanager_install_dir }}/{{ item }}"
        owner: "{{ alertmanager_user }}"
        group: "{{ alertmanager_group }}"
        mode: '0755'
        remote_src: yes
      loop:
        - alertmanager
        - amtool

    - name: Clean up downloaded files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
        - "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64"

- name: Copy Alertmanager configuration
  template:
    src: alertmanager.yml.j2
    dest: "{{ alertmanager_config_dir }}/alertmanager.yml"
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
    mode: '0644'
  notify: restart alertmanager

- name: Copy Alertmanager systemd service file
  template:
    src: alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service
    mode: '0644'
  notify: restart alertmanager

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable and start Alertmanager service
  systemd:
    name: alertmanager
    enabled: yes
    state: started
