---
galaxy_info:
  author: Doul Sy
  description: PostgreSQL database server role with replication
  company: Your Company
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - buster
        - bullseye
  galaxy_tags:
    - database
    - postgresql
    - replication

dependencies: []
